// keys
export const FIELD_KEY_INITIAL_VALUE = 'initialValue'
export const FIELD_KEY_INITIAL_VALUE_ERROR = 'initialValueError'
export const FIELD_KEY_DIRTY = 'dirty'
export const FIELD_KEY_ERROR = 'error'
export const FIELD_KEY_FOCUS = 'focus'
export const FIELD_KEY_TOUCHED = 'touched'
export const FIELD_KEY_VALID = 'valid'
export const FIELD_KEY_VALUE = 'value'
export const FIELD_KEY_VALUE_ON_FOCUS = 'valueOnFocus'
