// default values for keys
export const FIELD_DEFAULT_DEFAULT_VALUE = undefined
export const FIELD_DEFAULT_DEFAULT_VALUE_ERROR = undefined
export const FIELD_DEFAULT_DIRTY = false
export const FIELD_DEFAULT_ERROR = null
export const FIELD_DEFAULT_FOCUS = false
export const FIELD_DEFAULT_TOUCHED = false
export const FIELD_DEFAULT_VALID = true
export const FIELD_DEFAULT_VALUE = undefined
export const FIELD_DEFAULT_VALUE_ON_FOCUS = null
