import { FieldStateType, NamespaceStateType } from '../common'
import {
  FIELD_KEY_INITIAL_VALUE,
  FIELD_KEY_INITIAL_VALUE_ERROR,
  FIELD_KEY_DIRTY,
  FIELD_KEY_ERROR,
  FIELD_KEY_FOCUS,
  FIELD_KEY_TOUCHED,
  FIELD_KEY_VALID,
  FIELD_KEY_VALUE,
  FIELD_KEY_VALUE_ON_FOCUS,
} from './field-keys'
import {
  FIELD_DEFAULT_DEFAULT_VALUE,
  FIELD_DEFAULT_DEFAULT_VALUE_ERROR,
  FIELD_DEFAULT_DIRTY,
  FIELD_DEFAULT_ERROR,
  FIELD_DEFAULT_FOCUS,
  FIELD_DEFAULT_TOUCHED,
  FIELD_DEFAULT_VALID,
  FIELD_DEFAULT_VALUE,
  FIELD_DEFAULT_VALUE_ON_FOCUS,
} from './field-defaults'

export const FIELD_STATE_DEFAULT: FieldStateType = {
  [FIELD_KEY_ERROR]: FIELD_DEFAULT_ERROR,
  [FIELD_KEY_VALID]: FIELD_DEFAULT_VALID,
  [FIELD_KEY_VALUE]: FIELD_DEFAULT_VALUE,
  [FIELD_KEY_DIRTY]: FIELD_DEFAULT_DIRTY,
  [FIELD_KEY_FOCUS]: FIELD_DEFAULT_FOCUS,
  [FIELD_KEY_TOUCHED]: FIELD_DEFAULT_TOUCHED,
  [FIELD_KEY_VALUE_ON_FOCUS]: FIELD_DEFAULT_VALUE_ON_FOCUS,
  [FIELD_KEY_INITIAL_VALUE]: FIELD_DEFAULT_DEFAULT_VALUE,
  [FIELD_KEY_INITIAL_VALUE_ERROR]: FIELD_DEFAULT_DEFAULT_VALUE_ERROR,
}
Object.freeze(FIELD_STATE_DEFAULT)

export const NAMESPACE_STATE_DEFAULT: NamespaceStateType = {}
Object.freeze(NAMESPACE_STATE_DEFAULT)
